In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Importing WordCloud for Text Visualization
from wordcloud import WordCloud

# Importing nltk for natural language processing
import nltk
from nltk.corpus import stopwords

# Downloading nltk data
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ashimgrg/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /Users/ashimgrg/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [2]:
df = pd.read_csv('spam.csv')

df.head()

     v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [3]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [4]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace=True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
# Rename the columns
df.rename(columns = {'v1':'target','v2':'text'},inplace=True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

<h4>Data Preprocessing<h4>

In [6]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [7]:
# Check Duplicate values
df.duplicated().sum()

403

In [8]:
len(df)

5572

In [ ]:
# Deleting the duplicated values

df = df.drop_duplicates(keep='first')
len(df)

5169

<h4>Feature Engineering Part<h4>

In [13]:
# Importing the Porter Stemmer for text stemming
from nltk.stem.porter import PorterStemmer

# Importing string module to handle special strings
import string

pc = PorterStemmer()

In [31]:
# Lowercase Transformation and text processing function
def transform_text(text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenize the text
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove the stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
            
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    
    for i in text:
        y.append(pc.stem(i))
        
    # Join the processed tokens back to a single string
    return ' '.join(y)

In [32]:
transform_text('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [33]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

   target  ...                                   transformed_text
0       0  ...  go jurong point crazi avail bugi n great world...
1       0  ...                              ok lar joke wif u oni
2       1  ...  free entri 2 wkli comp win fa cup final tkt 21...
3       0  ...                u dun say earli hor u c alreadi say
4       0  ...               nah think goe usf live around though

[5 rows x 3 columns]

<h4>Vectorize the transformed text <h4>

In [35]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
tfid = TfidfVectorizer(max_features=500)

In [38]:
X = tfid.fit_transform(df['transformed_text']).toarray()
y = df['target'].values

<h4>Train Test Split<h4>

In [49]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,BaggingClassifier,ExtraTreesClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

In [52]:
svc = SVC(kernel='sigmoid',gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear',penalty='l1')
rfc = RandomForestClassifier(n_estimators=50,random_state=2)
abc = AdaBoostClassifier(n_estimators=50,random_state=2)
bc = BaggingClassifier(n_estimators=50,random_state=2)
etc = ExtraTreesClassifier(n_estimators=50,random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier()

In [59]:
clfs = {
    'svc':svc,
    'knc':knc,
    'mnb':mnb,
    'dtc':dtc,
    'lrc':lrc,
    'rfc':rfc,
    'abc':abc,
    'bc':bc,
    'etc':etc,
    'gbdt':gbdt,
    'xgb':xgb
}

<h4>Model Evaluation Part<h4>

In [65]:
from sklearn.metrics import accuracy_score,precision_score
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    return accuracy,precision

In [66]:
accuracy_scores, precision_scores = [],[]

for name, clf in clfs.items():
    current_accuracy,current_precision = train_classifier(clf,X_train,y_train,X_test,y_test)
    print('\nFor: ',name)
    print('Accuracy: ',current_accuracy)
    print('Precision: ',current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For:  svc
Accuracy:  0.9709864603481625
Precision:  0.952755905511811

For:  knc
Accuracy:  0.9294003868471954
Precision:  0.9736842105263158

For:  mnb
Accuracy:  0.9758220502901354
Precision:  0.9838709677419355

For:  dtc
Accuracy:  0.9313346228239845
Precision:  0.8303571428571429

For:  lrc
Accuracy:  0.9574468085106383
Precision:  0.904

For:  rfc
Accuracy:  0.971953578336557
Precision:  0.953125

For:  abc
Accuracy:  0.9158607350096711
Precision:  0.7959183673469388

For:  bc
Accuracy:  0.960348162475822
Precision:  0.8768115942028986

For:  etc
Accuracy:  0.9777562862669246
Precision:  0.9552238805970149

For:  gbdt
Accuracy:  0.9477756286266924
Precision:  0.941747572815534

For:  xgb
Accuracy:  0.9671179883945842
Precision:  0.9172932330827067